run apt-get install -y python-numpy
run apt-get install -y python-scipy
run apt-get install -y git
run apt-get install -y python-pip
#setup workspace
run mkdir ~/tsad
WORKDIR ~/tsad
run git clone https://github.com/HIPS/Spearmint.git
run pip install -e /Spearmint

